# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ufittapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for ufittapp

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end

target 'ufittapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ufittapp-tvOS

  target 'ufittapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
