# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ufittapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ufittapp
   pod 'FirebaseMessaging'
  pod 'Firebase/Core'

  target 'ufittappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ufittapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ufittapp-tvOS

  target 'ufittapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
